import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import { useRouter } from 'next/router';
import { PostCard, Categories, PostWidget, Loader } from '../../components';
import { getCategories, getCategoryPosts } from '../../services';
import Link from 'next/link';;

export default function Home( { posts, category }) {
  const router = useRouter();

  if (router.isFallback) {
    return <Loader />;
  }

  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>What is Andy Doing NOW?!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='transition duration-700 mb-8 cursor-pointer hover:text-pink-600 text-3xl'>
        {`#${category}`}
      </h1>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <div className="lg:col-span-8 col-span-1">
          {posts.map((post) => <PostCard post={post.node} key={post.node.title} />)}
        </div>
        <div className="lg:col-span-4 col-span-1">
           <div className="lg:sticky relative top-8">
            <PostWidget />
            <Categories />
           </div>
        </div>
      </div>
    </div>
  )
}

export async function getStaticProps({ params }) {
  const categories = await getCategoryPosts(params.slug);
  return {
    props: { 
      posts: categories.edges,
      category: params.slug
    }
  }
}

export async function getStaticPaths() {
  const categories = await getCategories();
  return {
    paths: categories.map(({ slug }) => (
      { params: { slug } }
    )),
    fallback: false
  }
}